Do not apply FORTIFY_SOURCE to Debug builds, since they use -O0
/usr/include/features.h:451:4: error: #warning _FORTIFY_SOURCE requires
compiling with optimization (-O) [-Werror=cpp]

Signed-off-by: darkexplosiveqwx <101737077+darkexplosiveqwx@users.noreply.github.com>