Update common.c
Hi,
it seems that after the DB-Changes the following spot was changed incorrectly

/opt/FTL/src/database/common.c: In function ‘create_counter_table’:
/opt/FTL/src/database/common.c:138:21: error: implicit conversion from ‘enum ftl_table_props’ to ‘const enum counters_table_props’ [-Werror=enum-conversion]
  138 |  db_set_counter(db, DB_FIRSTCOUNTERTIMESTAMP, (unsigned long)time(0));
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~

I think this fixes it.

Regards
Petr

Signed-off-by: Petr Cech <cech@flora.cechovi.org>